### ISSUE TITLE
Fix Anime API on home page

### ISSUE THREAD

**Issue by amanjagdev** [amanjagdev/aniverse#3]
On the Home page of the site, popular anime should be fetched and displayed on the screen.
This feature is not working and needs to be fixed
![to_be_fixed](https://user-images.githubusercontent.com/34389172/94770187-981cbb00-03d1-11eb-9759-1674787e4193.png)

**Comment by anup-a** [comment]
Can I pickup this one ?

**Comment by amanjagdev** [comment]
> Can I pickup this one ?

Yes, sure I hope you understand what is needed to be added in the documentation. Please do the following and make a pull request for the same. 
Feel free to ping if you need any more information on this.
I am assigning you to this issue.

**Comment by amanjagdev** [comment]
I hope you understand what feature is needed to be added. Please do the following and make a pull request for the same. Feel free to ping me if you encounter any problem while understanding the project structure.
Shall I assign this issue to you?

**Comment by anup-a** [comment]
Sure you can assign me

**Comment by anup-a** [comment]
You want to display popular anime at home page ? or any random 10 animes?

**Comment by amanjagdev** [comment]
> You want to display popular anime at home page ? or any random 10 animes?

If you could do for popular animes then it would be good... but random anime would also work.

**Comment by amanjagdev** [comment]
It is successfully fixed
