### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by amanjagdev** [amanjagdev/aniverse#4]
The documentation doesn't provide much detail about the project and there is not enough information.

Documentation must cover these topics:
- Project Description along with usage GIF or screenshots
- Technologies used
- Getting Started: Local installation guide
- Contributing guide

**Comment by navya252001** [comment]
I am from IITBHU
Please assign it me

**Comment by amanjagdev** [comment]
Okay, sure you can work on this...
Please do a detailed guide regarding this that also includes screenshots of the actual application.. you may use an open-source template for this if you like...
For the technologies used: It's based on react-js for the most part :)

PS: I have opened up an issue in your to-do-list repo .. Do check it out. I would be happy to contribute.

**Comment by navya252001** [comment]
Ok thankyou

**Comment by amanjagdev** [comment]
Issue Resolved
