### ISSUE TITLE
Add Transition and Animation

### ISSUE THREAD

**Issue by amanjagdev** [amanjagdev/aniverse#7]
Some sort of animation needs to be added when transitioning to different components 
And there should be a smooth transition added to elements so that content load abruptly.

Moreover, elements of the site look static as there are no hover animations or effects
Above mentioned feature must be implemented to improve UI and UX of the app

**Comment by wilsantow** [comment]
@amanjagdev can I work on this ?

**Comment by amanjagdev** [comment]
@wilsantow  Yes you can but what approach will you follow regarding this. can you please explain In brief

**Comment by wilsantow** [comment]
I am thinking of using framer-motion library for animations.

**Comment by amanjagdev** [comment]
Okay, Great... You can start working on this..

**Comment by wilsantow** [comment]
@amanjagdev Hey, I opened a pull request, can you check and merge it?

**Comment by amanjagdev** [comment]
@wilsantow  Done :)
This issue is resolved.
